#!/bin/bash

FILE=/tmp/firstboot

if [ ! -f "$FILE" ]; then
  apt-get update
  apt-get -y install python3 python3-pip postgresql

  python3 -m pip install bs4
  python3 -m pip install datetime
  python3 -m pip install requests
  python3 -m pip install psycopg2-binary
fi

while [ condition ]
do
   python3 /scripts/python-OSRS-highscore/osrsHighscore.py
   sleep 1h
done
