#!/bin/bash

FILE=/tmp/firstboot

if test -f "$FILE"; then
  apt-get update python3
  apt-get -y install python3 python3-pip postgresql

  python -m pip install bs4
  python -m pip install datetime
  python -m pip install requests
  python -m pip install psycopg2-binary
fi

while [ condition ]
do
   python3 /scripts/python-OSRS-highscore/osrsHighscore.py
   sleep 1h
done
