#!/bin/bash

DBCONFIGFILE=/config/database.ini
if [ ! -f "$DBCONFIGFILE" ]; then
  echo '[postgresql]' > $DBCONFIGFILE
  echo "host=${db_host}" >> $DBCONFIGFILE
  echo "database=${db_database}" >> $DBCONFIGFILE
  echo "user=${db_user}" >> $DBCONFIGFILE
  echo "password=${db_password}" >> $DBCONFIGFILE
fi

OSRSPLAYERSFILE=/config/osrs_players
if [ ! -f "$OSRSPLAYERSFILE" ]; then
  echo "$osrs_players" > $OSRSPLAYERSFILE
fi

tz=$(date +%z)
echo ${tz::3} > /config/tz

cron -f
