#!/bin/bash

DBCONFIGFILE=/config/database.ini
if [ ! -f "$DBCONFIGFILE" ]; then
  echo '[postgresql]' > $DBCONFIGFILE
  echo "host=${db_host}" >> $DBCONFIGFILE
  echo "database=${db_database}" >> $DBCONFIGFILE
  echo "user=${db_user}" >> $DBCONFIGFILE
  echo "password=${db_password}" >> $DBCONFIGFILE
fi

OSRSPLAYERSFILE=/config/osrs_players
if [ ! -f "$OSRSPLAYERSFILE" ]; then
  touch $OSRSPLAYERSFILE
  for PLAYER in "${osrs_players[@]}"; do
    echo "$PLAYER" >> $OSRSPLAYERSFILE
  done
fi

cron -f
